src/Entity/Event.php
<?php

namespace App\Entity;

use App\Repository\EventRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: EventRepository::class)]
class Event
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $title = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $description = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTime $creation_date = null;

    #[ORM\Column(type: Types::DATE_MUTABLE, nullable: true)]
    private ?\DateTime $modification_date = null;

    #[ORM\ManyToOne(inversedBy: 'events')]
    private ?User $user = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): static
    {
        $this->title = $title;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): static
    {
        $this->description = $description;

        return $this;
    }

    public function getCreationDate(): ?\DateTime
    {
        return $this->creation_date;
    }

    public function setCreationDate(\DateTime $creation_date): static
    {
        $this->creation_date = $creation_date;

        return $this;
    }

    public function getModificationDate(): ?\DateTime
    {
        return $this->modification_date;
    }

    public function setModificationDate(?\DateTime $modification_date): static
    {
        $this->modification_date = $modification_date;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): static
    {
        $this->user = $user;

        return $this;
    }
}

src/Form/EventType.php
<?php

namespace App\Form;

use App\Entity\Event;
use App\Entity\User;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class EventType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('title')
            ->add('description')
            ->add('creation_date')
            // ->add('modification_date')
            // ->add('user', EntityType::class, [
            //     'class' => User::class,
            //     'choice_label' => 'id',
            // ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Event::class,
        ]);
    }
}

src/Controller/EventController.php
<?php

namespace App\Controller;

use App\Entity\Event;
use App\Form\EventType;
use App\Repository\EventRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;

#[Route('/event')]
final class EventController extends AbstractController
{
    #[Route(name: 'app_event_index', methods: ['GET'])]
    public function index(EventRepository $eventRepository): Response
    {
        return $this->render('event/index.html.twig', [
            'events' => $eventRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_event_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $event = new Event();
        $form = $this->createForm(EventType::class, $event);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($event);
            $entityManager->flush();

            return $this->redirectToRoute('app_event_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('event/new.html.twig', [
            'event' => $event,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_event_show', methods: ['GET'])]
    public function show(Event $event): Response
    {
        return $this->render('event/show.html.twig', [
            'event' => $event,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_event_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Event $event, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(EventType::class, $event);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_event_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('event/edit.html.twig', [
            'event' => $event,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_event_delete', methods: ['POST'])]
    public function delete(Request $request, Event $event, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$event->getId(), $request->getPayload()->getString('_token'))) {
            $entityManager->remove($event);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_event_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/event/_delete_form.html.twig
<form method="post" action="{{ path('app_event_delete', {'id': event.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ event.id) }}">
    <button class="btn btn-dark btnColor">Supprimer</button>
</form>

templates/event/_form.html.twig
{{ form_start(form) }}
    <div class="my-custom-class-for-errors">
            {{ form_errors(form) }}
    </div>
    {{ form_widget(form) }}
    <div class="d-flex justify-content-end">
        <button class="btn btn-dark mt-2">{{ button_label|default('Créer') }}</button>
    </div>
{{ form_end(form) }}

templates/event/edit.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <h1 class="text-center m-5">Modifier si vous osez !</h1>

    <div class="container log register">

        {{ include('event/_form.html.twig', {'button_label': 'Modifier'}) }}


        {{ include('event/_delete_form.html.twig') }}
    </div>
{% endblock %}

templates/event/index.html.twig
{% extends 'base.html.twig' %}

{% block body %}
<div class="container mt-5">
    <h1 class="box-index1 text-center mt-5">Les Événements</h1>
    {% if app.user %}
        <h2 class="text-center fs-4 mt-5">Bonjour <span class="purple text-decoration-underline">{{ app.user.pseudo}}</span>, nous espérons ( ou pas ) que vous ferez le bon choix .. </h2>
    {% endif %}

    {% for event in events %}
        <div class="m-5 d-flex justify-content-center">
            <a href="{{ path('app_event_show', {'id': event.id}) }}" class="btn btn-dark btn-lg col-8"><span>{{ event.title}}</span></a>
        </div>
    {% else %}
        <p>Il n'y a pas encore d'événement</p>
    {% endfor %}
    <div class="d-flex justify-content-center">
        <a href="{{ path('app_event_new') }}" class="btn colorIcons btn-dark margin-bot"><i class="fa-solid fa-ghost"></i> Créer un Événement</a>
    </div>
</div>
{% endblock %}

templates/event/new.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <h1 class="text-center mt-5">Quel sera le prochain enlève..évènement ?</h1>
    <div class="container log register text-light mt-5">
        {{ include('event/_form.html.twig') }}
    </div>
    {# <a href="{{ path('app_event_index') }}">back to list</a> #}
{% endblock %}

templates/event/show.html.twig
{% extends 'base.html.twig' %}
 
 
{% block body %}

    <div class="container">
        <h1 class="mt-5 text-center box-index1">Voici l'évènement </h1>
    </div>
    <div class="container-fluid mt-5 margin-bot">
        <div class="d-flex justify-content-center border-dark">
            <div class="card text-center border-dark" style="width: 48%;">
                <div class="card-header bg-dark box-form">
                    <h2>{{ event.title }}</h2>
                </div>
                <div class="card-body box-desc">
                    <p class="text-color">{{ event.description }}<p>
                </div>
                <div class="card-body bg-dark box-form">
                    {% if event.modificationDate %}
                        <p>Date de modification : {{ event.modificationDate ? event.modificationDate|date('d-m-Y') : ''}}</p>
                    {% else %}
                        <p>Date de création : {{ event.creationDate ? event.creationDate|date('d-m-Y') : '' }}<p>
                    {% endif %}
                    <a href="{{ path('app_event_edit', {'id': event.id}) }}" class="btn btn-dark btnColor">Modifier</a>
                    {% if app.user and app.user == event.user %}
                       
                    {% endif %}
 
                    {% if is_granted('ROLE_ADMIN') %}
                        {{ include('event/_delete_form.html.twig') }}
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
{% endblock %}